[workspace]
members = ["crates/dsperse"]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
rmpv = { version = "1", features = ["with-serde"] }
rmp-serde = "1"
thiserror = "2"
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rayon = "1"
ndarray = { version = "0.16", features = ["serde"] }
tract-onnx = "0.21"
uuid = { version = "1", features = ["v4"] }
tempfile = "3"
prost = "0.13"
pyo3 = { version = "0.24" }
jstprove_circuits = { git = "https://github.com/inference-labs-inc/JSTprove.git", rev = "ba2d483" }
