[graph]
targets = []
all-features = false

[advisories]
yanked = "warn"

[licenses]
unlicensed = "allow"
allow-osi-fsf-free = "either"
default = "allow"
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-git = [
    "https://github.com/inference-labs-inc/JSTprove.git",
]
