[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "dsperse"
version = "0.0.0"
description = "Distributed zkML Toolkit"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [{ name = "Inference Labs", email = "info@inferencelabs.com" }]

[project.scripts]
dsperse = "dsperse.cli:main"

[tool.maturin]
features = ["python"]
module-name = "dsperse._native"
python-source = "python"
manifest-path = "crates/dsperse/Cargo.toml"
